### ISSUE TITLE
Does the certificate option select the p12 file?

### ISSUE THREAD

**Issue by fdjkpoi** [ROM-Knowledgeware/IPASign#14]
Select p12 file, prompt：failed to parse the given signing certificate
ios_development.cer ：The cer file is downloaded without a password
I have tested both of them and can't sign them.

**Comment by ROM-Knowledgeware** [comment]
You did not provide enough details for me to understand what steps are you taking.
Your singing certificate must be a .p12 file containing both the public and private key in order to sign IPAs.

**Comment by John0King** [comment]
@ROM-Knowledgeware    "failed to parse the given signing certificate"  is caused by `BouncyCastle`  `new Pkcs12Store(stream, password)`  with `IOExpction : {"attempt to add existing attribute with different value"}`

do you know how to fix it ?

I test with `new System.Security.Cryptography.X509Certificates.X509Certificate2(path,password)`  and it do not show the error
