### ISSUE TITLE
Got AppexBundleIDNotPrefixed during installation after resinging

### ISSUE THREAD

**Issue by anshumanchatterji** [ROM-Knowledgeware/IPASign#8]
> Installing 'com.*'
> Install: CreatingStagingDirectory (5%)
> Install: ExtractingPackage (15%)
> Install: InspectingPackage (20%)
> Install: TakingInstallLock (20%)
> Install: PreflightingApplication (30%)
> ERROR: Install failed. Got error "AppexBundleIDNotPrefixed" with code 0x00000000: Appex bundle at "/private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.A6wFkO/extracted/Payload/haima.app/PlugIns/HMtool.appex" with identifier "com.phelia.sociaten.tool" does not have expected identifier prefix "com.*."

Although, the error itself is confusing for me as it says **com.phelia.sociaten.tool** does not have expected identifier prefix **com.***. Do i need to use an exact AppIdentifer in the certificate? Currently i am using a wildcard AppIdentifer i.e. **com.***

**Comment by anshumanchatterji** [comment]
Here is the ipa file https://filebin.net/ebmnkv3tz95fqai4/AudioTube_v1.7.ipa?t=q36bfp40

**Comment by ROM-Knowledgeware** [comment]
1. Wildcard application identifiers are currently not supported, usually this prevents you from singing the IPA in the first place.
2. I'm not sure what signing certificate you are using, and since your CFBundleIdentifier (in Info.plist) is 'br.com.mobizera.audiotube' I'm not sure where the 'com.phelia.sociaten.tool' comes from.
3. You can't use wildcard for the app identifier itself. 'com.*' can be used to match application identifiers, it can't be the application identifier itself.
